version: "3"



services: 
    prometheus:
        image: prom/prometheus:v2.27.0
        ports: 
            - 9090:9090
        volumes: 
            - ./prometheus/data:/prometheus
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        # command: 
        #     - '--config.file=/etc/prometheus/prometheus.yml'


    grafana:

        image: grafana/grafana:7.5.6
        # depends_on: 
        #     - prometheus
        ports:
            - 3000:3000
        user: "0"
        volumes: 
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        # env_file: 
        #     - config.file

    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports: 
            - 9093:9093
        # volumes: 
        #     - ./alertmanager/:/etc/alertmanager/





